// Mocks generated by Mockito 5.4.5 from annotations
// in patientcareapp/test/data/repositories/favorites_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:patientcareapp/core/services/favorites_service.dart' as _i2;
import 'package:patientcareapp/data/models/favorite_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FavoritesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesService extends _i1.Mock implements _i2.FavoritesService {
  @override
  _i3.Future<List<_i4.FavoriteModel>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.FavoriteModel>>.value(<_i4.FavoriteModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.FavoriteModel>>.value(<_i4.FavoriteModel>[]),
      ) as _i3.Future<List<_i4.FavoriteModel>>);

  @override
  _i3.Future<void> addFavorite(_i4.FavoriteModel? favorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [favorite],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isFavorite(
    String? itemId,
    String? itemType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [
            itemId,
            itemType,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
